###
POST http://localhost:8080/Users/register
Content-Type: application/json

{
  "name": "Juan",
  "middleName": "Carlos",
  "surname": "Pérez",
  "secondSurname": "García",
  "documentNumber": "12345678901",
  "age": 28,
  "dateOfBirth": "19961215",
  "phone": "3001234567",
  "email": "juan.perez@example.com",
  "password": "SecurePass123!"
}