-- =========================================================================
-- V1__init_schema.sql
-- Creación inicial reflejando exactamente las entidades Java actuales
-- =========================================================================

-- 1. TABLA PRINCIPAL: users (Basado en la entidad User)
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       name VARCHAR(100) NOT NULL,
                       middle_name VARCHAR(100),
                       last_name VARCHAR(100) NOT NULL,
                       second_surname VARCHAR(100),
                       document_number VARCHAR(11) NOT NULL,
                       age INTEGER NOT NULL,
                       date_of_birth VARCHAR(10) NOT NULL,
                       phone VARCHAR(10) NOT NULL,
                       email VARCHAR(150) NOT NULL,
                       password VARCHAR(100) NOT NULL,
                       CONSTRAINT pk_users PRIMARY KEY (id),
                       CONSTRAINT uc_users_document_number UNIQUE (document_number),
                       CONSTRAINT uc_users_email UNIQUE (email)
);

-- 2. TABLA: current_balances (Basado en la entidad MoneyNow)
CREATE TABLE current_balances (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  id_user BIGINT NOT NULL,
                                  current_balance DECIMAL NOT NULL,
                                  date_register TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                  CONSTRAINT pk_current_balances PRIMARY KEY (id),
                                  CONSTRAINT uc_current_balances_id_user UNIQUE (id_user),
                                  CONSTRAINT fk_current_balances_on_id_user FOREIGN KEY (id_user) REFERENCES users (id)
);

-- 3. TABLA: expenses (Basado en la entidad RegisterExpense)
CREATE TABLE expenses (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          movement_type VARCHAR(255) NOT NULL,
                          expense_value DECIMAL NOT NULL,
                          date_movement_expense TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                          movement_note VARCHAR(255),
                          id_user BIGINT NOT NULL,
                          CONSTRAINT pk_expenses PRIMARY KEY (id),
                          CONSTRAINT fk_expenses_on_id_user FOREIGN KEY (id_user) REFERENCES users (id)
);

-- 4. TABLA: savings (Basado en la entidad SaveMoney)
CREATE TABLE savings (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         movement_type VARCHAR(255) NOT NULL,
                         savings_value DECIMAL NOT NULL,
                         date_movement_income TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                         movement_note VARCHAR(100),
                         id_user BIGINT NOT NULL,
                         CONSTRAINT pk_savings PRIMARY KEY (id),
                         CONSTRAINT fk_savings_on_id_user FOREIGN KEY (id_user) REFERENCES users (id)
);

-- 5. TABLA: savings_money_users (Basado en la entidad SavingsMoneyUsers)
CREATE TABLE savings_money_users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     user_id BIGINT NOT NULL,
                                     name_savings VARCHAR(255) NOT NULL,
                                     amount DECIMAL NOT NULL,
                                     date_of_registry TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     CONSTRAINT pk_savings_money_users PRIMARY KEY (id),
                                     CONSTRAINT fk_savings_money_users_on_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);

-- 6. TABLA: savings_plan_id (Basado en la entidad SavingsPlan)
CREATE TABLE savings_plan_id (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                 name_plan VARCHAR(255) NOT NULL,
                                 meta_plan DECIMAL NOT NULL,
                                 description_plan_savings VARCHAR(255) NOT NULL,
                                 user_id BIGINT NOT NULL,
                                 CONSTRAINT pk_savings_plan_id PRIMARY KEY (id),
                                 CONSTRAINT fk_savings_plan_id_on_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);

-- 7. TABLA: savings_movements (Basado en la entidad SavingsMovements)
CREATE TABLE savings_movements (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                   amount DECIMAL NOT NULL,
                                   date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                   savings_plan_id BIGINT NOT NULL,
                                   CONSTRAINT pk_savings_movements PRIMARY KEY (id),
                                   CONSTRAINT fk_savings_movements_on_savings_plan_id FOREIGN KEY (savings_plan_id) REFERENCES savings_plan_id (id)
);