CREATE TABLE ahorros
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "valor-ahorrado"          DOUBLE PRECISION                        NOT NULL,
    "fecha-movimento-ingreso" TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    "nota-movimiento"         VARCHAR(100),
    "id-user"                 BIGINT                                  NOT NULL,
    CONSTRAINT pk_ahorros PRIMARY KEY (id)
);

CREATE TABLE gastos
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "valor-gasto"            DOUBLE PRECISION                        NOT NULL,
    "fecha-movimiento-gasto" TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    "nota-movimiento"        VARCHAR(255),
    "id-user"                BIGINT                                  NOT NULL,
    CONSTRAINT pk_gastos PRIMARY KEY (id)
);

CREATE TABLE "saldo-actual"
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_user        BIGINT                                  NOT NULL,
    saldo_actual   DOUBLE PRECISION                        NOT NULL,
    fecha_registro TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT "pk_saldo-actual" PRIMARY KEY (id)
);

CREATE TABLE usuarios
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre                       VARCHAR(100)                            NOT NULL,
    "segundo nombre"             VARCHAR(100),
    apellido                     VARCHAR(100)                            NOT NULL,
    "segundo apellido"           VARCHAR(100),
    numero_documento             VARCHAR(11)                             NOT NULL,
    age                          INTEGER                                 NOT NULL,
    fecha_nacimiento             VARCHAR(10)                             NOT NULL,
    telefono                     VARCHAR(10)                             NOT NULL,
    email                        VARCHAR(150)                            NOT NULL,
    password                     VARCHAR(100)                            NOT NULL,
    "numero-intentos-contraseña" INTEGER                                 NOT NULL,
    CONSTRAINT pk_usuarios PRIMARY KEY (id)
);

ALTER TABLE "saldo-actual"
    ADD CONSTRAINT "uc_saldo-actual_id_user" UNIQUE (id_user);

ALTER TABLE usuarios
    ADD CONSTRAINT uc_usuarios_email UNIQUE (email);

ALTER TABLE usuarios
    ADD CONSTRAINT uc_usuarios_numero_documento UNIQUE (numero_documento);

ALTER TABLE ahorros
    ADD CONSTRAINT "FK_AHORROS_ON_ID-USER" FOREIGN KEY ("id-user") REFERENCES usuarios (id);

ALTER TABLE gastos
    ADD CONSTRAINT "FK_GASTOS_ON_ID-USER" FOREIGN KEY ("id-user") REFERENCES usuarios (id);

ALTER TABLE "saldo-actual"
    ADD CONSTRAINT "FK_SALDO-ACTUAL_ON_ID_USER" FOREIGN KEY (id_user) REFERENCES usuarios (id);