CREATE TABLE users.users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(100)                            NOT NULL,
    middle_name     VARCHAR(100),
    last_name       VARCHAR(100)                            NOT NULL,
    second_surname  VARCHAR(100),
    document_number VARCHAR(11)                             NOT NULL,
    date_of_birth   VARCHAR(10)                             NOT NULL,
    phone           VARCHAR(10)                             NOT NULL,
    email           VARCHAR(150)                            NOT NULL,
    password        VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users.users
    ADD CONSTRAINT uc_users_document_number UNIQUE (document_number);

ALTER TABLE users.users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

CREATE TABLE movement_money_normal.current_balances
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_user         BIGINT                                  NOT NULL,
    current_balance DECIMAL                                 NOT NULL,
    date_register   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_current_balances PRIMARY KEY (id)
);

CREATE TABLE movement_money_normal.expenses
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    movement_type         VARCHAR(255)                            NOT NULL,
    expense_value         DECIMAL                                 NOT NULL,
    date_movement_expense TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    movement_note         VARCHAR(255),
    id_user               BIGINT                                  NOT NULL,
    CONSTRAINT pk_expenses PRIMARY KEY (id)
);

CREATE TABLE movement_money_normal.limit_expense
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_user             BIGINT                                  NOT NULL,
    value_limit         DECIMAL                                 NOT NULL,
    expiration_date     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    date_registry_limit TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_limit_expense PRIMARY KEY (id)
);

CREATE TABLE movement_money_normal.savings
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    movement_type        VARCHAR(255)                            NOT NULL,
    savings_value        DECIMAL                                 NOT NULL,
    date_movement_income TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    movement_note        VARCHAR(100),
    id_user              BIGINT                                  NOT NULL,
    CONSTRAINT pk_savings PRIMARY KEY (id)
);

ALTER TABLE movement_money_normal.current_balances
    ADD CONSTRAINT uc_current_balances_id_user UNIQUE (id_user);

ALTER TABLE movement_money_normal.limit_expense
    ADD CONSTRAINT uc_limit_expense_id_user UNIQUE (id_user);

ALTER TABLE movement_money_normal.current_balances
    ADD CONSTRAINT FK_CURRENT_BALANCES_ON_ID_USER FOREIGN KEY (id_user) REFERENCES users.users (id);

ALTER TABLE movement_money_normal.expenses
    ADD CONSTRAINT FK_EXPENSES_ON_ID_USER FOREIGN KEY (id_user) REFERENCES users.users (id);

ALTER TABLE movement_money_normal.limit_expense
    ADD CONSTRAINT FK_LIMIT_EXPENSE_ON_ID_USER FOREIGN KEY (id_user) REFERENCES users.users (id);

ALTER TABLE movement_money_normal.savings
    ADD CONSTRAINT FK_SAVINGS_ON_ID_USER FOREIGN KEY (id_user) REFERENCES users.users (id);

CREATE TABLE savings.savings_money_users
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    name_savings     VARCHAR(255)                            NOT NULL,
    amount           DECIMAL                                 NOT NULL,
    date_of_registry TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_savings_money_users PRIMARY KEY (id)
);

CREATE TABLE savings.savings_movements
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount          DECIMAL                                 NOT NULL,
    date            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    savings_plan_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_savings_movements PRIMARY KEY (id)
);

CREATE TABLE savings.savings_plan_id
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_plan                VARCHAR(255)                            NOT NULL,
    meta_plan                DECIMAL                                 NOT NULL,
    description_plan_savings VARCHAR(255),
    user_id                  BIGINT                                  NOT NULL,
    CONSTRAINT pk_savings_plan_id PRIMARY KEY (id)
);

ALTER TABLE savings.savings_money_users
    ADD CONSTRAINT FK_SAVINGS_MONEY_USERS_ON_USER FOREIGN KEY (user_id) REFERENCES users.users (id);

ALTER TABLE savings.savings_movements
    ADD CONSTRAINT FK_SAVINGS_MOVEMENTS_ON_SAVINGS_PLAN FOREIGN KEY (savings_plan_id) REFERENCES savings.savings_plan_id (id);

ALTER TABLE savings.savings_plan_id
    ADD CONSTRAINT FK_SAVINGS_PLAN_ID_ON_USER FOREIGN KEY (user_id) REFERENCES users.users (id);