CREATE TABLE IF NOT EXISTS movement_money_normal.limit_expense
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_user             BIGINT                                  NOT NULL,
    value_limit         DECIMAL                                 NOT NULL,
    expiration_date     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    date_registry_limit TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_limit_expense PRIMARY KEY (id)
);

ALTER TABLE movement_money_normal.limit_expense
    ADD CONSTRAINT uc_limit_expense_id_user UNIQUE (id_user);

ALTER TABLE movement_money_normal.limit_expense
    ADD CONSTRAINT FK_LIMIT_EXPENSE_ON_ID_USER FOREIGN KEY (id_user) REFERENCES users.users (id);

